import type * as THREE from "three";
import type { FutbahlLocomotionController } from "@/lib/futbahl-locomotion";
import type { BodyPresetId, PlayerLine } from "@/lib/anonymous-team-setup";

export type MatchState = "menu" | "playing" | "ended";
export type TeamId = "home" | "away";
export type PlayerId = string;
export type PlayerRole = "field" | "keeper";
export type PlayPhase = "open" | "goal" | "halftime" | "kickoff" | "throw-in" | "goal-kick" | "corner";
export type BoundaryRestartPhase = Extract<PlayPhase, "throw-in" | "goal-kick" | "corner">;
export type AiSkillMove = "shot-fake" | "body-feint" | "quick-turn" | "dribble-burst" | "fake-pass" | "rainbow-flick"
  | "scoop-turn" | "roulette" | "elastico" | "hocus-pocus" | "stepovers" | "phantom-dribble" | null;
export type KeeperAction = "none" | "intercept" | "smother" | "secure" | "distribute";
export type PostWinState = "none" | "WIN_BALL_CONTROL" | "POST_WIN_DECISION";
export type DefensivePressureRole = "press" | "cover" | "shape";
export type DefensiveTacticalRole = DefensivePressureRole
  | "mark-striker"
  | "mark-runner"
  | "block-lane"
  | "midfield-screen"
  | "wide-cover"
  | "far-post-cover"
  | "depth-cover";
export type DefensiveDangerPhase = "NORMAL_BLOCK" | "DEEP_BLOCK" | "EMERGENCY_GOAL_DEFENSE";
export type FirstTouchType = "foot" | "thigh" | "chest";
export type BallBoundaryState = "IN_PLAY" | "TOUCHLINE_OUT" | "GOAL_LINE_OUT" | "GOAL";
export type TutorialStatus = "active" | "success" | "complete";
export type LocomotionState = "idle" | "walk" | "jog" | "run" | "sprint" | "acceleration" | "deceleration"
  | "sharp-turn" | "lateral-shuffle" | "backpedal" | "dribble-jog" | "dribble-sprint"
  | "pass-approach" | "shot-approach" | "recovery";
export type BallTouchBodyPart = "foot" | "head" | "chest" | "knee" | "other";
export type BallTouchAction = "pass" | "clearance" | "shot" | "deflection" | "control" | "tackle" | "throwIn";

export type BallTouchRecord = {
  teamId: TeamId;
  playerId: PlayerId;
  bodyPart: BallTouchBodyPart;
  action: BallTouchAction;
  intentional: boolean;
  intendedReceiverId?: PlayerId;
  time: number;
};

export type TutorialRuntime = {
  active: boolean;
  lessonIndex: number;
  status: TutorialStatus;
  lessonTimer: number;
  successTimer: number;
  target: THREE.Vector3;
  targetPlayerId: string | null;
  initialControlledId: string | null;
  initialFullscreen: boolean;
  chargePeak: number;
  defendTimer: number;
  scenarioActionDone: boolean;
};

export type DefensiveTeamPlan = {
  defendingTeam: TeamId;
  carrierId: string;
  dangerPhase: DefensiveDangerPhase;
  primaryPresserId: string | null;
  secondaryCoverId: string | null;
  deepestThreatId: string | null;
  deepestMarkerId: string | null;
  aerialReceiverId: string | null;
  aerialMarkerId: string | null;
  aerialCoverId: string | null;
  roles: Map<string, DefensiveTacticalRole>;
  targets: Map<string, THREE.Vector3>;
  markedOpponentIds: Map<string, string>;
};

export type PlayerBody = {
  id: string;
  team: TeamId;
  role: PlayerRole;
  line: PlayerLine;
  number: number;
  formationSlot: string;
  home: THREE.Vector3;
  pos: THREE.Vector3;
  vel: THREE.Vector3;
  mesh: THREE.Group;
  controlMarker: THREE.Object3D | null;
  receiverMarker: THREE.Object3D | null;
  aimArrow: THREE.Object3D | null;
  possessionLabel: THREE.Object3D | null;
  parts: PlayerAnimationParts;
  bodyPresetId: BodyPresetId;
  preferredFoot: "left" | "right";
  heading: number;
  turnRate: number;
  stamina: number;
  sprintExhausted: boolean;
  runPhase: number;
  distanceTravelled: number;
  previousHorizontalSpeed: number;
  locomotionState: LocomotionState;
  locomotionBlend: number;
  animationSpeed: number;
  kickTimer: number;
  animationKickStyle: KickStyle | null;
  actionCooldown: number;
  tackleTimer: number;
  tackleCooldown: number;
  recoveryTimer: number;
  catchTimer: number;
  diveTimer: number;
  diveSide: number;
  headerTimer: number;
  previousHeadWorldPosition: THREE.Vector3;
  headerSampleFrame: number;
  firstTouchTimer: number;
  firstTouchType: FirstTouchType | null;
  receiveControlTimer: number;
  receiveIncomingSpeed: number;
  receiveControlQuality: number;
  blockTimer: number;
  passRequestTimer: number;
  celebrateTimer: number;
  yellowCards: number;
  sentOff: boolean;
  decisionCooldown: number;
  carryTimer: number;
  stuckTimer: number;
  contactLockTimer: number;
  fallbackTimer: number;
  fallbackTarget: THREE.Vector3;
  lastPos: THREE.Vector3;
  animationLastPos: THREE.Vector3;
  frameStartPos: THREE.Vector3;
  supportRunTimer: number;
  supportRunTarget: THREE.Vector3;
  skillTimer: number;
  skillCooldown: number;
  skillSide: number;
  skillMove: AiSkillMove;
  aiInputCache: PlayerInputState;
  aiInputTimer: number;
  forcedMoveTarget: THREE.Vector3;
  forcedMoveTimer: number;
  forcedMoveSprint: boolean;
  setPieceTarget: THREE.Vector3;
  setPieceAssignmentActive: boolean;
  ballContactCooldown: number;
  challengeCommitTimer: number;
  keeperAction: KeeperAction;
  keeperActionTimer: number;
  keeperClaimPoint: THREE.Vector3;
  postWinState: PostWinState;
  postWinTimer: number;
  previousInputDir: THREE.Vector3;
  locomotionController: FutbahlLocomotionController | null;
  controlledBy?: "p1";
};

export type PlayerAnimationParts = {
  bodyRoot: THREE.Object3D | null;
  pelvis: THREE.Object3D | null;
  spineLower: THREE.Object3D | null;
  spineUpper: THREE.Object3D | null;
  chest: THREE.Object3D | null;
  neckBase: THREE.Object3D | null;
  neckTop: THREE.Object3D | null;
  head: THREE.Object3D | null;
  headContact: THREE.Object3D | null;
  leftClavicle: THREE.Object3D | null;
  rightClavicle: THREE.Object3D | null;
  leftLeg: THREE.Object3D | null;
  rightLeg: THREE.Object3D | null;
  leftKnee: THREE.Object3D | null;
  rightKnee: THREE.Object3D | null;
  leftFoot: THREE.Object3D | null;
  rightFoot: THREE.Object3D | null;
  leftArm: THREE.Object3D | null;
  rightArm: THREE.Object3D | null;
  leftElbow: THREE.Object3D | null;
  rightElbow: THREE.Object3D | null;
  leftHand: THREE.Object3D | null;
  rightHand: THREE.Object3D | null;
};

export type BallState = "loose" | "possessed" | "kicked";
export type KickStyle = "short" | "long" | "through" | "low-through" | "shot" | "driven" | "finesse" | "chip";
export type ManualKickKind = "pass" | "loft" | "shot";
export type ManualRestartZone = "near" | "center" | "far" | "edge" | "short" | "direct";

export type PlayerInputState = {
  dir: THREE.Vector3;
  sprint: boolean;
  speedScale?: number;
};

export type MinimapSnapshot = {
  ball: { x: number; z: number };
  players: Array<{ id: string; team: TeamId; x: number; z: number; controlled: boolean }>;
};

export type ReplayPlayerSnapshot = {
  id: string;
  x: number;
  z: number;
  heading: number;
  runPhase: number;
  kickTimer: number;
  catchTimer: number;
  diveTimer: number;
  diveSide: number;
};

export type ReplayFrame = {
  ball: { x: number; y: number; z: number };
  players: ReplayPlayerSnapshot[];
};

export type GameSessionAnalytics = {
  id: string | null;
  startedAt: number;
  startedScore: { home: number; away: number };
};

export type TutorialLessonDefinition = {
  title: string;
  instruction: string;
  key: string;
};

export type PassIntentState = "prepare" | "track" | "control";

export type PassIntent = {
  passerId: string;
  receiverId: string;
  receiverTeamId: TeamId;
  kickTime: number;
  passType: "short" | "driven" | "through" | "lob" | "clearance";
  state: PassIntentState;
  initialDirection: THREE.Vector3;
  target: THREE.Vector3;
  predictedReceptionPoint: THREE.Vector3;
  predictedArrivalTime: number;
  initialPower: number;
  elapsed: number;
  intoSpace: boolean;
};

export type PendingReceiveAction = {
  receiverId: PlayerId;
  action: "oneTouchPass" | "quickPass" | "control";
  passStyle?: "short" | "through" | "low-through";
  nextReceiverId?: PlayerId;
  targetPosition?: THREE.Vector3;
  requestedAt: number;
  expiresAt: number;
  requestedBy: "user" | "ai";
  estimatedIncomingSpeed?: number;
  requiredControlTime?: number;
  oneTouchEligible?: boolean;
};

export type CrowdAudioBuffers = {
  ambient: AudioBuffer | null;
  swell: AudioBuffer | null;
  goal: AudioBuffer | null;
};

export type WhistleEvent = "kickoff-first" | "kickoff-second" | "halftime" | "fulltime" | "foul" | "penalty";

export type PendingKickContact = {
  playerId: string;
  receiverId: string | null;
  style: KickStyle;
  remaining: number;
  contactPosition: THREE.Vector3;
  velocity: THREE.Vector3;
  curve: THREE.Vector3;
  angularVelocity: THREE.Vector3;
  grounded: boolean;
  direction: THREE.Vector3;
  target: THREE.Vector3;
  power: number;
  touchAction: BallTouchAction;
  ignoreTimer: number;
  soundVolume: number;
};

export type MatchRuntime = {
  engineId: number;
  renderer: THREE.WebGLRenderer;
  scene: THREE.Scene;
  camera: THREE.PerspectiveCamera;
  cameraLookAt: THREE.Vector3;
  cameraFocusZ: number;
  cameraTouchlineBlend: number;
  cameraMode: "broadcast" | "first-person";
  ball: THREE.Group;
  ballShadow: THREE.Mesh;
  players: PlayerBody[];
  frame: number;
  frameRunning: boolean;
  matchTick: number | null;
  frameCount: number;
  lastTime: number;
  lastRenderTime: number;
  lastMatchUpdate: number;
  lastClockAdvanceTime: number;
  lastHudUpdate: number;
  state: MatchState;
  phase: PlayPhase;
  phaseTimer: number;
  restartTeam: TeamId;
  restartSpot: THREE.Vector3;
  restartDirection: THREE.Vector3;
  restartActorId: string | null;
  half: 1 | 2;
  gameClock: number;
  halftimeDone: boolean;
  eventText: string;
  eventTimer: number;
  ballPos: THREE.Vector3;
  previousBallPhysicsPos: THREE.Vector3;
  ballVisualPosition: THREE.Vector3;
  ballPhysicsAccumulator: number;
  ballGrounded: boolean;
  ballRollingDistance: number;
  ballAngularVelocity: THREE.Vector3;
  ballCollisionCount: number;
  ballPhysicsSubsteps: number;
  ballFrictionState: "airborne" | "sliding" | "rolling" | "sleeping";
  ballVel: THREE.Vector3;
  ballCurve: THREE.Vector3;
  score: { home: number; away: number };
  possessionTime: { home: number; away: number };
  cooldown: number;
  possession: TeamId | null;
  ballState: BallState;
  ballOwnerId: string | null;
  intendedReceiverId: string | null;
  passIntent: PassIntent | null;
  pendingReceiveAction: PendingReceiveAction | null;
  passTargetMarker: THREE.Object3D;
  kickPreviewGuide: THREE.Line;
  kickPreviewLine: THREE.Mesh;
  kickPreviewEndpoint: THREE.Mesh;
  kickLandingZone: THREE.Group;
  adBoardTexture: THREE.CanvasTexture;
  adBrandIndex: number;
  adBrandTimer: number;
  adBoardBounces: number;
  passIntentsCreated: number;
  passIntentsResolved: number;
  passIntentsAbandoned: number;
  manualPassReceiverId: string | null;
  ballIgnorePlayerId: string | null;
  ballIgnoreTimer: number;
  looseContactPlayerId: string | null;
  looseContactCooldownTimer: number;
  receptionLockPlayerId: string | null;
  receptionLockTimer: number;
  possessionStableOwnerId: string | null;
  possessionStabilityTimer: number;
  attackingPossessionTeam: TeamId | null;
  attackingPossessionTimer: number;
  ballStuckTimer: number;
  goalLineStallTimer: number;
  touchlineStallTimer: number;
  boundaryState: BallBoundaryState;
  ballStuckProbe: THREE.Vector3;
  ballStuckRecoveries: number;
  overlappingBallPlayerIds: string[];
  ownershipWindowTimer: number;
  ownershipTransitionsInWindow: number;
  ownershipTransitionsPerSecond: number;
  lastObservedOwnerId: string | null;
  contactPairDurations: Map<string, number>;
  gluedPairRecoveries: number;
  maxContactPairDuration: number;
  frameStartPositions: Map<string, THREE.Vector3>;
  defensivePlan: DefensiveTeamPlan | null;
  defensivePlanTimer: number;
  defensivePlanGraceTimer: number;
  antiSwarmCorrections: number;
  collisionResolutionsThisFrame: number;
  maxCollisionCorrection: number;
  maxDefenderFrameDisplacement: number;
  abnormalMovementClamps: number;
  lastAbnormalMovementPlayerId: string | null;
  lastAbnormalMovementSource: string;
  looseBallCollectorId: string | null;
  looseBallCollectorTimer: number;
  looseBallInterceptTarget: THREE.Vector3;
  looseBallCollectorIds: Record<TeamId, string | null>;
  looseBallCollectorTimers: Record<TeamId, number>;
  looseBallInterceptTargets: Record<TeamId, THREE.Vector3>;
  looseBallCollectorAssignments: number;
  pendingKickTarget: THREE.Vector3 | null;
  pendingKickContact: PendingKickContact | null;
  lastShotTap: number;
  shotCharge: number;
  shotChargingPlayerId: string | null;
  passCharge: number;
  passChargingPlayerId: string | null;
  passCommitTimer: number;
  trajectoryDiagnosticActive: boolean;
  loftCharge: number;
  loftChargingPlayerId: string | null;
  manualRestartTargetId: string | null;
  manualRestartTargetZone: ManualRestartZone | null;
  manualGoalKickTarget: THREE.Vector3 | null;
  shotInputLockTimer: number;
  shotConsumed: boolean;
  tackleLockTimer: number;
  audio: AudioContext | null;
  activeAudioSources: Set<AudioScheduledSourceNode>;
  scheduledTimeouts: Set<number>;
  crowdAmbienceSources: Set<AudioBufferSourceNode>;
  crowdAmbienceGains: Set<GainNode>;
  crowdMasterGain: GainNode | null;
  crowdLimiter: DynamicsCompressorNode | null;
  crowdAmbienceSession: number;
  crowdAmbienceTimer: number | null;
  crowdAudioBuffers: CrowdAudioBuffers;
  crowdAudioLoading: Promise<void> | null;
  crowdAudioLoaded: boolean;
  crowdAudioUnavailable: boolean;
  crowdAudioWarningLogged: boolean;
  whistleAudioBuffer: AudioBuffer | null;
  whistleAudioLoading: Promise<void> | null;
  whistleAudioUnavailable: boolean;
  lastWhistleEventKey: string;
  lastWhistleEventTime: number;
  lastCrowdSwellTime: number;
  lastGoalCrowdTime: number;
  lastCommentaryTime: number;
  lastCommentaryCue: string;
  lastKickSound: number;
  lastCheerSound: number;
  lastTouchTeam: TeamId;
  lastTouchPlayerId: string | null;
  lastTouchRecord: BallTouchRecord | null;
  restartProtectionTeam: TeamId | null;
  restartProtectionTimer: number;
  goalKickLockPlayerId: string | null;
  goalKickLockTimer: number;
  goalKickReleaseTimer: number;
  goalKickPendingVelocity: THREE.Vector3;
  goalKickPendingReceiverId: string | null;
  manualGoalKickReceiverId: string | null;
  restartBoundaryGuardTimer: number;
  setPieceReleaseActive: boolean;
  setPieceReleaseOrigin: THREE.Vector3;
  setPieceReleaseActorId: string | null;
  setPieceReleaseBlend: number;
  pendingRestartPhase: BoundaryRestartPhase | null;
  pendingRestartTeam: TeamId;
  pendingRestartSpot: THREE.Vector3;
  pendingRestartLabel: string;
  pendingRestartTimer: number;
  p1IdleTimer: number;
  p1Autopilot: boolean;
  lastManualAim: THREE.Vector3;
  lastManualAimTimer: number;
  manualAimReceiverId: string | null;
  manualAimLockTimer: number;
  passInputDownAt: number;
  passInputAttempts: number;
  passInputExecuted: number;
  passInputRejected: number;
  pendingInputMovementAt: number;
  pendingInputMovementStart: THREE.Vector3;
  perfElement: HTMLDivElement | null;
  perfFrames: number;
  perfFrameTotal: number;
  perfFrameSamples: number[];
  perfFrameSampleIndex: number;
  perfLongTaskCount: number;
  perfLongTaskTotal: number;
  perfMaxLongTask: number;
  perfInputLatencies: number[];
  perfAiTotal: number;
  perfAiSamples: number;
  perfRendererTotal: number;
  perfRendererSamples: number;
  perfLastReport: number;
  replayTimer: number;
  replayBallStart: THREE.Vector3;
  replayBallEnd: THREE.Vector3;
  replayCameraPosition: THREE.Vector3;
  replayCameraLookAt: THREE.Vector3;
  replayTrail: THREE.Vector3[];
  replayFrames: ReplayFrame[];
  restartCount: number;
  matchGeneration: number;
  lifecycleEpoch: number;
  fullTimeHandled: boolean;
  fullTimeTransitions: number;
  matchUpdatesThisFrame: number;
  visibilityPauseCount: number;
  restartSeed: number;
  keeperClaimAttempts: number;
  keeperClaims: number;
  keeperSmothers: number;
  emergencyBlockAttempts: number;
  emergencyBlocks: number;
  postWinRecoveries: number;
  postWinAbandons: number;
  blockedPassCancellations: number;
  blockedPassAlternatives: number;
  boxFinishingDecisions: number;
  contextualSkillAttempts: number;
  contextualSkillsTriggered: number;
  locomotionDebugElement: HTMLDivElement | null;
  locomotionAttachGeneration: number;
  rosterSignature: string;
  tutorial: TutorialRuntime;
};
